# Generated by Django 2.2.19 on 2021-03-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0001_combined'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiStatusEmailNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='kpistatusemailnotification',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ilm_server_2.KpiStatusEmailNotificationType'),
            preserve_default=False,
        ),
    ]
