# Generated by Django 2.2.12 on 2021-03-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0002_auto_20210324_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contacts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='ilm_server_2.Contact'),
        ),
    ]
