# Generated by Django 2.2.19 on 2021-03-31 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0003_auto_20210330_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
