# Generated by Django 2.2.19 on 2021-04-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0006_newsupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personcontact',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
