# Generated by Django 2.2.19 on 2021-04-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0008_auto_20210405_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworkactivitytype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ilm_server_2.FieldworkActivityTypeCategory'),
        ),
    ]
