# Generated by Django 2.2.20 on 2021-04-09 08:37

from django.db import migrations, models
import issara.ilm_server_2.models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0010_auto_20210408_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('SP', 'Strategic Partner'), ('RA', 'Recruitment Agency'), ('S', 'Supplier'), ('IS', 'Issara Staff'), ('O', 'Other')], default='O', max_length=2)),
                ('file_path', models.FileField(blank=True, null=True, upload_to=issara.ilm_server_2.models.SharedFile.get_upload_path)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'shared_files',
                'managed': True,
            },
        ),
    ]
