# Generated by Django 2.2.19 on 2021-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0011_sharedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierkpi',
            name='closed_quality',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplierkpiupdate',
            name='closed_quality',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=10, null=True),
        ),
    ]
