# Generated by Django 2.2.19 on 2021-04-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0012_auto_20210420_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicpartner',
            name='imageicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ilm_server_2.SharedFile'),
        ),
    ]
