# Generated by Django 2.2.20 on 2021-04-23 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('ilm_server_2', '0013_strategicpartner_imageicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicPartnerUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='strategic_partner_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('strategic_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilm_server_2.StrategicPartner')),
            ],
            options={
                'verbose_name_plural': 'Strategic partner users',
                'db_table': 'strategic_partner_users',
                'managed': True,
            },
        ),
    ]
