# Generated by Django 2.2.20 on 2021-04-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0014_strategicpartneruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategicpartner',
            name='partner_users',
        ),
    ]
