# Generated by Django 2.2.20 on 2021-05-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0015_remove_strategicpartner_partner_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='imageicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ilm_server_2.SharedFile'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='type',
            field=models.CharField(choices=[('SP', 'Strategic Partner'), ('RA', 'Recruitment Agency'), ('S', 'Supplier'), ('IS', 'Issara Staff'), ('NF', 'Nationality Flag'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
