# Generated by Django 2.2.20 on 2021-05-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0016_auto_20210511_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='type',
            field=models.CharField(choices=[('SP', 'Strategic Partner'), ('RA', 'Recruitment Agency'), ('S', 'Supplier'), ('IS', 'Issara Staff'), ('NF', 'Nationality Flag'), ('O', 'Other')], default='O', max_length=4),
        ),
    ]
