# Generated by Django 2.2.20 on 2021-05-14 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilm_server_2', '0020_auto_20210511_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiEmailNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('days_gt', models.IntegerField(blank=True, null=True)),
                ('days_lt', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('email_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('kpi_status', models.ManyToManyField(to='ilm_server_2.SupplierKpiUpdateStatus')),
            ],
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='type',
            field=models.CharField(choices=[('NF', 'FlagIcon'), ('SP', 'Strategic Partner'), ('RA', 'Recruitment Agency'), ('S', 'Supplier'), ('IS', 'Issara Staff'), ('O', 'Other')], default='O', max_length=20),
        ),
        migrations.DeleteModel(
            name='KpiStatusEmailNotification',
        ),
        migrations.DeleteModel(
            name='KpiStatusEmailNotificationType',
        ),
    ]
