# Generated by Django 2.2.20 on 2021-05-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0023_auto_20210514_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiemailnotification',
            name='name',
        ),
    ]
