# Generated by Django 2.2.20 on 2021-05-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0024_remove_kpiemailnotification_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpiemailnotification',
            old_name='days_et',
            new_name='days_eq',
        ),
    ]
