# Generated by Django 2.2.20 on 2021-05-14 04:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilm_server_2', '0025_auto_20210514_0354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KpiEmailNotification',
            new_name='KpiEmailNotificationTemplate',
        ),
        migrations.AlterModelOptions(
            name='kpiemailnotificationtemplate',
            options={'verbose_name_plural': 'KPI Email Notification Templates'},
        ),
    ]
