# Generated by Django 2.2.20 on 2021-05-14 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ilm_server_2', '0026_auto_20210514_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiEmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('error_message', models.TextField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('supplier_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilm_server_2.SupplierKpi')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilm_server_2.KpiEmailNotificationTemplate')),
            ],
        ),
    ]
