# Generated by Django 2.2.20 on 2021-05-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0027_kpiemailnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpiemailnotificationtemplate',
            old_name='kpi_status',
            new_name='kpi_statuses',
        ),
    ]
