# Generated by Django 2.2.20 on 2021-05-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0028_auto_20210514_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiemailnotification',
            name='supplier_kpi',
        ),
        migrations.AddField(
            model_name='kpiemailnotification',
            name='supplier_kpis',
            field=models.ManyToManyField(to='ilm_server_2.SupplierKpi'),
        ),
    ]
