# Generated by Django 2.2.20 on 2021-05-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0029_auto_20210514_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiemailnotificationtemplate',
            name='days_gt',
        ),
        migrations.RemoveField(
            model_name='kpiemailnotificationtemplate',
            name='days_lt',
        ),
    ]
