# Generated by Django 2.2.20 on 2021-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0030_auto_20210514_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpiemailnotification',
            options={'verbose_name_plural': 'KPI Email Notifications'},
        ),
        migrations.AlterField(
            model_name='kpiemailnotification',
            name='supplier_kpis',
            field=models.ManyToManyField(related_name='notifications', to='ilm_server_2.SupplierKpi'),
        ),
    ]
