# Generated by Django 2.2.20 on 2021-05-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0031_auto_20210514_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='sort_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='sort_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
