# Generated by Django 2.2.23 on 2021-05-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0033_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
