# Generated by Django 2.2.23 on 2021-05-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0035_auto_20210528_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='loggedout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
