# Generated by Django 2.2.24 on 2021-06-12 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0036_auto_20210529_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='interacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='interaction_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ilm_server_2.InteractionChannel'),
        ),
        migrations.AddField(
            model_name='case',
            name='interaction_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ilm_server_2.InteractionReason'),
        ),
        migrations.AddField(
            model_name='case',
            name='interaction_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('Incoming', 'Incoming'), ('Outcoming', 'Outcoming')], default='Incoming', max_length=20, null=True),
        ),
    ]
