# Generated by Django 2.2.24 on 2021-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0039_auto_20210613_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='issue_offender_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='interactiontype',
            field=models.CharField(blank=True, choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], default='Incoming', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caseinteraction',
            name='type',
            field=models.CharField(blank=True, choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], default='Incoming', max_length=20, null=True),
        ),
    ]
