# Generated by Django 2.2.23 on 2021-07-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0041_case_risk_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
