# Generated by Django 2.2.24 on 2021-07-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0042_supplier_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierkpi',
            name='kpi_update_source',
            field=models.CharField(choices=[('supplierkpiupdateform', 'supplierkpiupdateform'), ('caseupdate', 'caseupdate')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierkpiupdate',
            name='kpi_update_source',
            field=models.CharField(choices=[('supplierkpiupdateform', 'supplierkpiupdateform'), ('caseupdate', 'caseupdate')], max_length=10, null=True),
        ),
    ]
