# Generated by Django 2.2.24 on 2021-07-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0043_auto_20210715_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierkpi',
            name='kpi_update_source',
            field=models.CharField(choices=[('supplierkpiupdateform', 'supplierkpiupdateform'), ('caseupdate', 'caseupdate')], max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='supplierkpiupdate',
            name='kpi_update_source',
            field=models.CharField(choices=[('supplierkpiupdateform', 'supplierkpiupdateform'), ('caseupdate', 'caseupdate')], max_length=512, null=True),
        ),
    ]
