# Generated by Django 2.2.24 on 2021-09-02 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0045_auto_20210902_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiemailnotificationtemplate',
            name='level_eq',
            field=models.PositiveIntegerField(blank=True, help_text='Level equals (min: 1, max: 4)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='kpiemailnotificationtemplate',
            name='level_gte',
            field=models.PositiveIntegerField(blank=True, help_text='Level greater than or equals (min: 1, max: 4)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='kpiemailnotificationtemplate',
            name='level_lte',
            field=models.PositiveIntegerField(blank=True, help_text='Level less than or equals (min: 1, max: 4)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
