# Generated by Django 2.2.24 on 2021-09-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0047_partnernewsupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnerNewsUpdate',
            new_name='PartnerMessageBoard',
        ),
        migrations.AlterModelOptions(
            name='partnermessageboard',
            options={'managed': True, 'verbose_name_plural': 'PartnerMessageBoards'},
        ),
    ]
