# Generated by Django 2.2.24 on 2021-09-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0048_auto_20210913_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiemailnotificationtemplate',
            name='golive',
            field=models.BooleanField(default=False),
        ),
    ]
