# Generated by Django 2.2.24 on 2021-09-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0049_kpiemailnotificationtemplate_golive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierkpi',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='ilm_server_2.Supplier'),
        ),
    ]
