# Generated by Django 2.2.24 on 2021-09-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0050_auto_20210922_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicpartneruser',
            name='strategic_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ilm_server_2.StrategicPartner'),
        ),
    ]
