# Generated by Django 2.2.24 on 2021-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilm_server_2', '0051_auto_20210922_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicpartneruser',
            name='email_notify',
            field=models.BooleanField(default=False),
        ),
    ]
