runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 6.0
  disk_size_gb: 10

handlers:
- url: /
  script: true
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: true
  secure: always
  redirect_http_response_code: 301

#liveness_check:
#  path: "/api/v1/info"
#  check_interval_sec: 30
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2

#handlers:
#  http_headers: 
#    Access-Control-Allow-Origin: "*"


#beta_settings:
#        cloud_sql_instances: ilm-app:us-west1:staging-1:3306

